apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: anilk13/java-ci:dev-106
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
  namespace: dev
spec:
  selector:
    app: k8s-demo # Must match the labels in Deployment
  ports:
  - protocol: TCP
    port: 80 # The port exposed by the Service
    targetPort: 8080 # The port inside the container
